rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
env:
  - CHEF_VERSION=
  - CHEF_VERSION="~> 10.16.4"
  - CHEF_VERSION="~> 10.14.4"
  - CHEF_VERSION="~> 0.10.10"
  - CHEF_VERSION="~> 0.9.18"
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
script: 'bundle exec thor spec:ci'
