rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
script: 'bundle exec thor spec:ci'
