rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.master
  - gemfiles/Gemfile.11
  - gemfiles/Gemfile.10
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: 2.0.0
    - gemfiles: gemfiles/Gemfile.master
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
script: 'bundle exec thor spec:ci'
